
BookNames <- Books
BookNames[1] <-  'Dictionary of Greek and Roman Geography: Vol. II'
BookNames[2] <- 'History of TACITUS: Book 1'
BookNames[3] <-  'The Pelopgnnesian War: Book V. Translated from the Greek of Thucydides'
BookNames[4] <- 'The History of the Decline and Fall of the Roman Empire: Vol 1. By Edward Gibbon'
BookNames[5] <- 'The History of Rome: Vol 1. By Titus Livius. Translated George Baker'
BookNames[6] <- 'Antiquities of the Jews: Book IX. Works of Josephus'
BookNames[7] <- 'The History of the Decline and Fall of the Roman Empire: Vol 3. By Edward Gibbon'
BookNames[8] <- 'The Description of Greece. By Paus Anias'
BookNames[9] <- 'The History of Rome: Vol 3. (Book4) By Theodor Mommsem'
BookNames[10] <- 'The History of Rome: Vol 3. Translated George Baker'
BookNames[11] <- 'The History of the Peloponnesian War: Vol/Book 1'
BookNames[12] <- 'The History of the Decline and Fall of the Roman Empire: Vol 4. By Edward Gibbon'
BookNames[13] <- 'The History of the Decline and Fall of the Roman Empire: Vol 2. By Edward Gibbon'
BookNames[14] <- 'The History of Rome: Book 1. By Titus Livius. Translated William Gordon'
BookNames[15] <- 'Annals of Tacitus: Vol I'
BookNames[16] <- 'The Jewish War: Book III. Works of Josephus'
BookNames[17] <- 'Annals of Tacitus: Vol IV. Book XV'
BookNames[18] <- 'The History of Rome: Vol 5. By Titus Livius Translated George Baker'
BookNames[19] <- 'Antiquities of the Jews: Book I. Works of Josephus'
BookNames[20] <- 'The natural History of Pliny: Book I. Plinius. Dedication'
BookNames[21] <- 'The History of the Decline and Fall of the Roman Empire: Vol 5. By Edward Gibbon'
BookNames[22] <- 'The History of Tacitus'
BookNames[23] <- 'The History of the Decline and Fall of the Roman Empire: Vol 6. By Edward Gibbon'
BookNames[24] <- 'Antiquities of the Jews: Book XVII. Works of Josephus'

BookNamesShort <- Books
BookNamesShort[1] <- 'Dictionary of Greek and Roman Geography'
BookNamesShort[2] <- 'History of Tacitus: Book 1'
BookNamesShort[3] <- 'The Pelopnnesian War: Book V'
BookNamesShort[4] <- 'Decline and Fall of the Roman Empire: Vol 1'
BookNamesShort[5] <- 'The History of Rome: Vol 1. Titus Livius'
BookNamesShort[6] <- 'Antiquities of the Jews: IX. Works of Josephus'
BookNamesShort[7] <- 'Decline and Fall of the Roman Empire: Vol 3'
BookNamesShort[8] <- 'The Description of Greece'
BookNamesShort[9] <- 'History of Rome: Vol 3. Theodor Mommsem'
BookNamesShort[10] <- 'History of Rome: Vol 3. Livy'
BookNamesShort[11] <- 'History of the Peloponnesian War: Book 1'
BookNamesShort[12] <- 'Decline and Fall of the Roman Empire: Vol 4'
BookNamesShort[13] <- 'Decline and Fall of the Roman Empire: Vol 2'
BookNamesShort[14] <- 'The History of Rome: Book 1. Titus Livius'
BookNamesShort[15] <- 'Annals of Tacitus: Vol I'
BookNamesShort[16] <- 'The Jewish War: Book III. Works of Josephus'
BookNamesShort[17] <- 'Annals of Tacitus: Vol IV'
BookNamesShort[18] <- 'The History of Rome: Vol 5. Titus Livius'
BookNamesShort[19] <- 'Antiquities of the Jews: I. Works of Josephus'
BookNamesShort[20] <- 'The natural History of Pliny: Book I'
BookNamesShort[21] <- 'Decline and Fall of the Roman Empire: Vol 5'
BookNamesShort[22] <- 'The History of Tacitus'
BookNamesShort[23] <- 'Decline and Fall of the Roman Empire: Vol 6'
BookNamesShort[24] <- 'Antiquities of the Jews: XVII. Works of Josephus'

BookNamesShorter <- Books
BookNamesShorter [1] <- 'Dictionary Greek and Roman Geog'
BookNamesShorter [2] <- 'History of Tacitus: Book 1'
BookNamesShorter [3] <- 'The Peloponnesian War V'
BookNamesShorter [4] <- 'Dec and Fall of Roman Empire 1'
BookNamesShorter [5] <- 'History of Rome 1. Titus Livius'
BookNamesShorter [6] <- 'Ant of Jews: IX. Josephus'
BookNamesShorter [7] <- 'Dec and Fall of Roman Empire 3'
BookNamesShorter [8] <- 'The Description of Greece'
BookNamesShorter [9] <- 'History of Rome: Vol 3. Mommsem'
BookNamesShorter [10] <- 'History of Rome: Vol 3. Livy'
BookNamesShorter [11] <- 'History of Peloponnesian War 1'
BookNamesShorter [12] <- 'Dec and Fall of Roman Empire 4'
BookNamesShorter [13] <- 'Dec and Fall of Roman Empire 2'
BookNamesShorter [14] <- 'History of Rome B 1. Titus Livius'
BookNamesShorter [15] <- 'Annals of Tacitus: Vol I'
BookNamesShorter [16] <- 'The Jewish War III. Josephus'
BookNamesShorter [17] <- 'Annals of Tacitus IV'
BookNamesShorter [18] <- 'The History of Rome 5. Titus Livius'
BookNamesShorter [19] <- 'Ant of Jews: I. Josephus'
BookNamesShorter [20] <- 'The natural History of Pliny'
BookNamesShorter [21] <- 'Dec and Fall of Roman Empire 5'
BookNamesShorter [22] <- 'The History of Tacitus'
BookNamesShorter [23] <- 'Dec and Fall of Roman Empire 6'
BookNamesShorter [24] <- 'Ant of Jews: XVII. Josephus'


BookNamesShortest <- Books
BookNamesShortest [1] <- 'Geo Dictionary'
BookNamesShortest [2] <- 'Tacitus 1'
BookNamesShortest [3] <- 'Peloponnesian War V'
BookNamesShortest [4] <- 'Fall of Rome 1'
BookNamesShortest [5] <- 'Livius 1'
BookNamesShortest [6] <- 'Josephus IX'
BookNamesShortest [7] <- 'Fall of Rome 3'
BookNamesShortest [8] <- 'Desc of Greece'
BookNamesShortest [9] <- 'Hist of Rome. Mommsem'
BookNamesShortest [10] <- 'Hist of Rome. Livy'
BookNamesShortest [11] <- 'Peloponnesian War 1'
BookNamesShortest [12] <- 'Fall of Rome 4'
BookNamesShortest [13] <- 'Fall of Rome 2'
BookNamesShortest [14] <- 'Livius 2'
BookNamesShortest [15] <- 'Tacitus Vol I'
BookNamesShortest [16] <- 'Josephus III'
BookNamesShortest [17] <- 'Tacitus IV'
BookNamesShortest [18] <- 'Livius 5'
BookNamesShortest [19] <- 'Josephus I'
BookNamesShortest [20] <- 'Pliny'
BookNamesShortest [21] <- 'Fall of Rome 5'
BookNamesShortest [22] <- 'Tacitus'
BookNamesShortest [23] <- 'Fall of Rome 6'
BookNamesShortest [24] <- 'Josephus XVII'